# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Debug'
    
steps:
- task: NuGetToolInstaller@1

- task: DownloadSecureFile@1
  name: deploymentAppsettings
  displayName: 'Download appsettings for Azure'
  inputs:
    secureFile: 'deploymentAppsettings.json'

- task: SqlDacpacDeploymentOnMachineGroup@0
  inputs:
    TaskType: 'sqlInline'
    InlineSql: |
      drop database if exists apsi;
                              create database apsi;
    ServerName: 'localhost'
    DatabaseName: 'apsi2019.database.windows.net'
    AuthScheme: 'sqlServerAuthentication'
    SqlUsername: 'apsi'
    SqlPassword: 'Qwerty2019.'
    AdditionalArgumentsSql: 'ConnectionTimeout=90;'
- task: CmdLine@2
  inputs:
    script: |
      cd app
      mv $(deploymentAppsettings.secureFilePath) .
      mv deploymentAppsettings.json appsettings.json
      dotnet tool install --global dotnet-ef --version 3.0
      dotnet ef database update --verbose

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure dla studentów(1)(6d784889-8525-48ae-8a5a-ddb25dd465d3)'
    appType: 'webApp'
    WebAppName: 'apsi2019'
    packageForLinux: '$(build.artifactStagingDirectory)\WebApp.zip'
