# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DownloadSecureFile@1
  name: deploymentAppsettings
  displayName: 'Download appsettings for Azure'
  inputs:
    secureFile: 'deploymentAppsettings.json'

- task: CmdLine@2
  inputs:
    script: |
      echo Migracja:
      echo %MIGRACJA%
      cd app
      mv $(deploymentAppsettings.secureFilePath) .
      mv deploymentAppsettings.json appsettings.json
      ls
      dotnet tool install --global dotnet-ef --version 3.0
      dotnet ef database update %MIGRACJA%