# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: SqlAzureDacpacDeployment@1
  inputs:
    azureSubscription: 'Azure dla studentów(6d784889-8525-48ae-8a5a-ddb25dd465d3)'
    AuthenticationType: 'server'
    ServerName: 'apsi2019.database.windows.net'
    DatabaseName: 'apsi'
    SqlUsername: 'apsi'
    SqlPassword: 'Qwerty2019.'
    deployType: 'InlineSqlTask'
    SqlInline: |
      IF OBJECT_ID(N'[__EFMigrationsHistory]') IS NULL
      BEGIN
          CREATE TABLE [__EFMigrationsHistory] (
              [MigrationId] nvarchar(150) NOT NULL,
              [ProductVersion] nvarchar(32) NOT NULL,
              CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY ([MigrationId])
          );
      END;
      
      GO
      
      IF NOT EXISTS(SELECT * FROM [__EFMigrationsHistory] WHERE [MigrationId] = N'00000000000000_CreateIdentitySchema')
      BEGIN
          CREATE TABLE [AspNetRoles] (
              [Id] nvarchar(450) NOT NULL,
              [Name] nvarchar(256) NULL,
              [NormalizedName] nvarchar(256) NULL,
              [ConcurrencyStamp] nvarchar(max) NULL,
              CONSTRAINT [PK_AspNetRoles] PRIMARY KEY ([Id])
          );
      END;
      
      GO
      
      IF NOT EXISTS(SELECT * FROM [__EFMigrationsHistory] WHERE [MigrationId] = N'00000000000000_CreateIdentitySchema')
      BEGIN
          CREATE TABLE [AspNetUsers] (
              [Id] nvarchar(450) NOT NULL,
              [UserName] nvarchar(256) NULL,
              [NormalizedUserName] nvarchar(256) NULL,
              [Email] nvarchar(256) NULL,
              [NormalizedEmail] nvarchar(256) NULL,
              [EmailConfirmed] bit NOT NULL,
              [PasswordHash] nvarchar(max) NULL,
              [SecurityStamp] nvarchar(max) NULL,
              [ConcurrencyStamp] nvarchar(max) NULL,
              [PhoneNumber] nvarchar(max) NULL,
              [PhoneNumberConfirmed] bit NOT NULL,
              [TwoFactorEnabled] bit NOT NULL,
              [LockoutEnd] datetimeoffset NULL,
              [LockoutEnabled] bit NOT NULL,
              [AccessFailedCount] int NOT NULL,
              CONSTRAINT [PK_AspNetUsers] PRIMARY KEY ([Id])
          );
      END;
      
      GO
      
      IF NOT EXISTS(SELECT * FROM [__EFMigrationsHistory] WHERE [MigrationId] = N'00000000000000_CreateIdentitySchema')
      BEGIN
          CREATE TABLE [DeviceCodes] (
              [UserCode] nvarchar(200) NOT NULL,
              [DeviceCode] nvarchar(200) NOT NULL,
              [SubjectId] nvarchar(200) NULL,
              [ClientId] nvarchar(200) NOT NULL,
              [CreationTime] datetime2 NOT NULL,
              [Expiration] datetime2 NOT NULL,
              [Data] nvarchar(max) NOT NULL,
              CONSTRAINT [PK_DeviceCodes] PRIMARY KEY ([UserCode])
          );
      END;
      
      GO
      
      IF NOT EXISTS(SELECT * FROM [__EFMigrationsHistory] WHERE [MigrationId] = N'00000000000000_CreateIdentitySchema')
      BEGIN
          CREATE TABLE [PersistedGrants] (
              [Key] nvarchar(200) NOT NULL,
              [Type] nvarchar(50) NOT NULL,
              [SubjectId] nvarchar(200) NULL,
              [ClientId] nvarchar(200) NOT NULL,
              [CreationTime] datetime2 NOT NULL,
              [Expiration] datetime2 NULL,
              [Data] nvarchar(max) NOT NULL,
              CONSTRAINT [PK_PersistedGrants] PRIMARY KEY ([Key])
          );
      END;
      
      GO
      
      IF NOT EXISTS(SELECT * FROM [__EFMigrationsHistory] WHERE [MigrationId] = N'00000000000000_CreateIdentitySchema')
      BEGIN
          CREATE TABLE [AspNetRoleClaims] (
              [Id] int NOT NULL IDENTITY,
              [RoleId] nvarchar(450) NOT NULL,
              [ClaimType] nvarchar(max) NULL,
              [ClaimValue] nvarchar(max) NULL,
              CONSTRAINT [PK_AspNetRoleClaims] PRIMARY KEY ([Id]),
              CONSTRAINT [FK_AspNetRoleClaims_AspNetRoles_RoleId] FOREIGN KEY ([RoleId]) REFERENCES [AspNetRoles] ([Id]) ON DELETE CASCADE
          );
      END;
      
      GO
      
      IF NOT EXISTS(SELECT * FROM [__EFMigrationsHistory] WHERE [MigrationId] = N'00000000000000_CreateIdentitySchema')
      BEGIN
          CREATE TABLE [AspNetUserClaims] (
              [Id] int NOT NULL IDENTITY,
              [UserId] nvarchar(450) NOT NULL,
              [ClaimType] nvarchar(max) NULL,
              [ClaimValue] nvarchar(max) NULL,
              CONSTRAINT [PK_AspNetUserClaims] PRIMARY KEY ([Id]),
              CONSTRAINT [FK_AspNetUserClaims_AspNetUsers_UserId] FOREIGN KEY ([UserId]) REFERENCES [AspNetUsers] ([Id]) ON DELETE CASCADE
          );
      END;
      
      GO
      
      IF NOT EXISTS(SELECT * FROM [__EFMigrationsHistory] WHERE [MigrationId] = N'00000000000000_CreateIdentitySchema')
      BEGIN
          CREATE TABLE [AspNetUserLogins] (
              [LoginProvider] nvarchar(128) NOT NULL,
              [ProviderKey] nvarchar(128) NOT NULL,
              [ProviderDisplayName] nvarchar(max) NULL,
              [UserId] nvarchar(450) NOT NULL,
              CONSTRAINT [PK_AspNetUserLogins] PRIMARY KEY ([LoginProvider], [ProviderKey]),
              CONSTRAINT [FK_AspNetUserLogins_AspNetUsers_UserId] FOREIGN KEY ([UserId]) REFERENCES [AspNetUsers] ([Id]) ON DELETE CASCADE
          );
      END;
      
      GO
      
      IF NOT EXISTS(SELECT * FROM [__EFMigrationsHistory] WHERE [MigrationId] = N'00000000000000_CreateIdentitySchema')
      BEGIN
          CREATE TABLE [AspNetUserRoles] (
              [UserId] nvarchar(450) NOT NULL,
              [RoleId] nvarchar(450) NOT NULL,
              CONSTRAINT [PK_AspNetUserRoles] PRIMARY KEY ([UserId], [RoleId]),
              CONSTRAINT [FK_AspNetUserRoles_AspNetRoles_RoleId] FOREIGN KEY ([RoleId]) REFERENCES [AspNetRoles] ([Id]) ON DELETE CASCADE,
              CONSTRAINT [FK_AspNetUserRoles_AspNetUsers_UserId] FOREIGN KEY ([UserId]) REFERENCES [AspNetUsers] ([Id]) ON DELETE CASCADE
          );
      END;
      
      GO
      
      IF NOT EXISTS(SELECT * FROM [__EFMigrationsHistory] WHERE [MigrationId] = N'00000000000000_CreateIdentitySchema')
      BEGIN
          CREATE TABLE [AspNetUserTokens] (
              [UserId] nvarchar(450) NOT NULL,
              [LoginProvider] nvarchar(128) NOT NULL,
              [Name] nvarchar(128) NOT NULL,
              [Value] nvarchar(max) NULL,
              CONSTRAINT [PK_AspNetUserTokens] PRIMARY KEY ([UserId], [LoginProvider], [Name]),
              CONSTRAINT [FK_AspNetUserTokens_AspNetUsers_UserId] FOREIGN KEY ([UserId]) REFERENCES [AspNetUsers] ([Id]) ON DELETE CASCADE
          );
      END;
      
      GO
      
      IF NOT EXISTS(SELECT * FROM [__EFMigrationsHistory] WHERE [MigrationId] = N'00000000000000_CreateIdentitySchema')
      BEGIN
          CREATE INDEX [IX_AspNetRoleClaims_RoleId] ON [AspNetRoleClaims] ([RoleId]);
      END;
      
      GO
      
      IF NOT EXISTS(SELECT * FROM [__EFMigrationsHistory] WHERE [MigrationId] = N'00000000000000_CreateIdentitySchema')
      BEGIN
          CREATE UNIQUE INDEX [RoleNameIndex] ON [AspNetRoles] ([NormalizedName]) WHERE [NormalizedName] IS NOT NULL;
      END;
      
      GO
      
      IF NOT EXISTS(SELECT * FROM [__EFMigrationsHistory] WHERE [MigrationId] = N'00000000000000_CreateIdentitySchema')
      BEGIN
          CREATE INDEX [IX_AspNetUserClaims_UserId] ON [AspNetUserClaims] ([UserId]);
      END;
      
      GO
      
      IF NOT EXISTS(SELECT * FROM [__EFMigrationsHistory] WHERE [MigrationId] = N'00000000000000_CreateIdentitySchema')
      BEGIN
          CREATE INDEX [IX_AspNetUserLogins_UserId] ON [AspNetUserLogins] ([UserId]);
      END;
      
      GO
      
      IF NOT EXISTS(SELECT * FROM [__EFMigrationsHistory] WHERE [MigrationId] = N'00000000000000_CreateIdentitySchema')
      BEGIN
          CREATE INDEX [IX_AspNetUserRoles_RoleId] ON [AspNetUserRoles] ([RoleId]);
      END;
      
      GO
      
      IF NOT EXISTS(SELECT * FROM [__EFMigrationsHistory] WHERE [MigrationId] = N'00000000000000_CreateIdentitySchema')
      BEGIN
          CREATE INDEX [EmailIndex] ON [AspNetUsers] ([NormalizedEmail]);
      END;
      
      GO
      
      IF NOT EXISTS(SELECT * FROM [__EFMigrationsHistory] WHERE [MigrationId] = N'00000000000000_CreateIdentitySchema')
      BEGIN
          CREATE UNIQUE INDEX [UserNameIndex] ON [AspNetUsers] ([NormalizedUserName]) WHERE [NormalizedUserName] IS NOT NULL;
      END;
      
      GO
      
      IF NOT EXISTS(SELECT * FROM [__EFMigrationsHistory] WHERE [MigrationId] = N'00000000000000_CreateIdentitySchema')
      BEGIN
          CREATE UNIQUE INDEX [IX_DeviceCodes_DeviceCode] ON [DeviceCodes] ([DeviceCode]);
      END;
      
      GO
      
      IF NOT EXISTS(SELECT * FROM [__EFMigrationsHistory] WHERE [MigrationId] = N'00000000000000_CreateIdentitySchema')
      BEGIN
          CREATE INDEX [IX_DeviceCodes_Expiration] ON [DeviceCodes] ([Expiration]);
      END;
      
      GO
      
      IF NOT EXISTS(SELECT * FROM [__EFMigrationsHistory] WHERE [MigrationId] = N'00000000000000_CreateIdentitySchema')
      BEGIN
          CREATE INDEX [IX_PersistedGrants_Expiration] ON [PersistedGrants] ([Expiration]);
      END;
      
      GO
      
      IF NOT EXISTS(SELECT * FROM [__EFMigrationsHistory] WHERE [MigrationId] = N'00000000000000_CreateIdentitySchema')
      BEGIN
          CREATE INDEX [IX_PersistedGrants_SubjectId_ClientId_Type] ON [PersistedGrants] ([SubjectId], [ClientId], [Type]);
      END;
      
      GO
      
      IF NOT EXISTS(SELECT * FROM [__EFMigrationsHistory] WHERE [MigrationId] = N'00000000000000_CreateIdentitySchema')
      BEGIN
          INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
          VALUES (N'00000000000000_CreateIdentitySchema', N'3.0.0');
      END;
      
      GO
      
      IF NOT EXISTS(SELECT * FROM [__EFMigrationsHistory] WHERE [MigrationId] = N'20191124231633_FirstMigration')
      BEGIN
          CREATE TABLE [Test] (
              [TestId] int NOT NULL,
              [TestName] nvarchar(256) NULL,
              CONSTRAINT [PK_Test] PRIMARY KEY ([TestId])
          );
      END;
      
      GO
      
      IF NOT EXISTS(SELECT * FROM [__EFMigrationsHistory] WHERE [MigrationId] = N'20191124231633_FirstMigration')
      BEGIN
          INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
          VALUES (N'20191124231633_FirstMigration', N'3.0.0');
      END;
      
      GO
    IpDetectionMethod: 'AutoDetect'